source 'https://cdn.cocoapods.org/'
source 'https://github.com/Buzzvil/Specs.git'

deployment_target = '11.0'

platform :ios, deployment_target

target 'buzzvil-sdk-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for buzzvil-sdk-ios
  pod 'BuzzvilSDK', '= 5.0.0-rc.1'

end
