FROM ruby:2-alpine

RUN apk add --no-cache git gomplate su-exec curl
RUN gem install cocoapods -v 1.6.2
RUN addgroup -S cocoapods && adduser -S cocoapods -G cocoapods
USER cocoapods
RUN pod setup
USER root
