platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Buzzvil/Specs.git'

use_frameworks!
inhibit_all_warnings!

deployment_target = '11.0'

target 'BABSample' do
  pod 'BuzzAdBenefit', '~> 3.27.4'
  pod 'Toast', '~> 4.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end
  end
end
