platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

target 'BABSample' do
  pod 'BuzzAdBenefitFeed', '~> 2.4.2'
  pod 'BuzzAdBenefitInterstitial', '~> 2.4.2'
  pod 'BuzzAdBenefitNative', '~> 2.4.2'
  pod 'Toast', '~> 4.0.0'
end

