source 'https://github.com/CocoaPods/Specs.git'

deployment_target = '13.0'

platform :ios, deployment_target

target 'buzzvil-sdk-ios-objc' do
  use_frameworks!
  
  pod 'BuzzvilSDK', '= 6.0.0'
end

target 'buzzvil-sdk-ios-swift' do
  use_frameworks!
  
  pod 'BuzzvilSDK', '= 6.0.0'
end

target 'buzzvil-sdk-ios-swiftui' do
  use_frameworks!
  
  pod 'BuzzvilSDK', '= 6.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end
  end
end
