// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvjYfLIKbpqxISMLR8kd76hlb5AjTlPsI',
    appId: '1:85060254161:android:0015d4d4e511c7dd5788f0',
    messagingSenderId: '85060254161',
    projectId: 'buzzbooster-e8131',
    storageBucket: 'buzzbooster-e8131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsoFTnOWw_MPx8Y__w3ohfyLgz8nlsJes',
    appId: '1:85060254161:ios:e7a0de3331c7c1255788f0',
    messagingSenderId: '85060254161',
    projectId: 'buzzbooster-e8131',
    storageBucket: 'buzzbooster-e8131.appspot.com',
    androidClientId: '85060254161-dmkabh8gsuecarupqegfj0bfdr9f1fja.apps.googleusercontent.com',
    iosClientId: '85060254161-tafh3t25adhrocaupln24ibklf1us846.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzBoosterFlutter',
  );
}
