platform :ios, '10.0'

source 'https://github.com/Buzzvil/Specs.git'
source ‘https://cdn.cocoapods.org/’

use_frameworks!
inhibit_all_warnings!

target 'BSTSample' do
  pod 'BuzzBooster', '= 0.1.2'
  pod 'Toast', '=4.0.0'
end
