platform :ios, '10.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Buzzvil/Specs/'

use_frameworks!
inhibit_all_warnings!

target 'BSTSample' do
  pod 'BuzzBooster', '~> 1.11.7'
  pod 'Toast', '=4.0.0'
end
