platform :ios, '11.0'

source 'https://cdn.cocoapods.org/'

use_frameworks!
inhibit_all_warnings!

target 'BSTSample' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'BuzzBoosterSDK', '~> 3.1.5'
  pod 'Toast', '=4.0.0'
end
